[project]
name = "sliia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "google-genai>=1.23.0",
    "google-generativeai>=0.8.5",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
]
